@startuml architecture

' Defined packages
package "Web Project" <<Application>> {    
    [WebApp.Common]
    [WebApp.Data]
    [WebApp.Services]
    [WebApp.Business]
    [WebApp.Web]
}

package "WebApp.Web" <<Layer>> {
    [Controllers]
    [Views]
    [Models]
    [Areas]
    [DependencyInjection]
}

package "WebApp.Business" <<Layer>> {
    [Services]
    [Interfaces]
}

package "WebApp.Data" <<Layer>> {
    [Repositories]  
    [Unit of Work]  
    [Context]
}

package "WebApp.Common" <<Layer>> {
    [DTOs]
    [Constants]
    [Extensions]
    [Helpers]
    [Models]
}

package "WebApp.Services" <<Layer>> {
    [Interfaces]
    [Implementations]
    [Email Service]
}

' Dependency between packages
WebApp.Web --> WebApp.Business : uses
WebApp.Web --> WebApp.Services : uses
WebApp.Business --> WebApp.Data : uses
WebApp.Services --> WebApp.Data : uses

@enduml